### ISSUE TITLE
stopping_criterion_frequency

### ISSUE THREAD

**Issue by ErosSph** [heidekrueger/bnelearn#2]
When I running run_experiments_pso.py, IDE points out “TypeError: set_logging() got an unexpected keyword argument 'stopping_criterion_frequency'”,  I want to know how to solve this problem.

**Comment by heidekrueger** [comment]
Hi Eros,
thanks for pointing this out. The stopping criterion feature has been removed from the package but apparently we forgot to update the pso script.

Can you try deleting/commenting out line 81 of the script and see if that works? (`stopping_criterion_frequency=stopping_criterion_frequency`)

**Comment by ErosSph** [comment]
Thank you very much for your answer. On the evening of the 13th (Beijing time), I tried to comment out the error, but found a more serious problem. I have found (self.writer.add_text) and (self.writer.add_graph) had errors that class CustomSummaryWriter to which it belongs does not have add_text and add_graph functions.

**Comment by heidekrueger** [comment]
Our `CustomSummaryWriter` is an extension of pytorch's `SummaryWriter`-wrapper for tensorboard. (see https://pytorch.org/docs/stable/tensorboard.html), those methods are part of the original `SummaryWriter` interface. I'm a bit surprised that you get those errors, I suspect that you might be missing some package dependencies.

Can you run the test-suite using `pytest` (See step 4 here: https://bnelearn.readthedocs.io/en/latest/usage/installation.html)?

**Comment by ErosSph** [comment]
When I only running experiment.py, there has no error. But when I run_experiments_pso.py, there is still a error that "AttributeError: 'NoneType' object has no attribute 'add_text'". I have read all the content you provided and tried it，but pytest have some errors. I have read all the content you provided and tried it. At present, pytest is 3 failed, 123 passed, 46 skipped, 10 xfailed, 142 warnings.
